version: "3.3"

services:
  symfony:
    build: .docker
    container_name: symfony
    volumes:
      - .:/application
      
  xampp:
    container_name: xamp
    image: tomsik68/xampp:${PHP_VERSION}
    ports:
      - 22:22
      - 80:80 
    volumes:
      - ./app:/www